import * as THREE from './three.module.js';
import {SoftwareRenderer} from './software-renderer.js';
import {BodyCity,STATIONS} from './simulation.js';
const $=id=>document.getElementById(id),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const sim=new BodyCity();let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('world-canvas'),antialias:true,alpha:false,powerPreference:'high-performance'})}catch(e){renderer=new SoftwareRenderer({canvas:$('world-canvas')});}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe9b3a0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xe9b3a0,25,55);const camera=new THREE.OrthographicCamera(-6.6,6.6,8,-8,.1,90);camera.position.set(0,17,13);camera.lookAt(0,0,-.4);scene.add(new THREE.HemisphereLight(0xfff4dc,0xaa657b,2.5));const sun=new THREE.DirectionalLight(0xffead0,3.1);sun.position.set(-7,14,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-9,right:9,top:10,bottom:-10});sun.shadow.normalBias=.03;scene.add(sun);
const mats={};function mat(color){return mats[color]??=new THREE.MeshStandardMaterial({color,roughness:.7,metalness:.03})}
function mesh(geo,color,parent=scene,x=0,y=0,z=0){const o=new THREE.Mesh(geo,mat(color));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
const box=(w,h,d,c,p,x,y,z)=>mesh(new THREE.BoxGeometry(w,h,d),c,p,x,y,z),sphere=(r,c,p,x,y,z)=>mesh(new THREE.SphereGeometry(r,12,8),c,p,x,y,z),cyl=(r,h,c,p,x,y,z)=>mesh(new THREE.CylinderGeometry(r,r,h,16),c,p,x,y,z);
const floor=box(13,.4,15,0xdba68d,scene,0,-.4,0);floor.renderOrder=-30;box(11.5,.12,13.4,0xf1c9a8,scene,0,-.12,0).renderOrder=-29;
// Soft toy-like cells around a functional play board.
for(let side of [-1,1])for(let z=-6;z<=6;z+=1.2){const c=sphere(.75,z%2?0xe9a491:0xe0a18f,scene,side*6.1,-.05,z);c.scale.y=.6}
function road(points,width,color){const y=width>1?.025:.07,path=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(p[0],y,p[1]))),v=[],ix=[];for(let i=0;i<=70;i++){const t=i/70,p=path.getPoint(t),d=path.getTangent(t),n=new THREE.Vector3(-d.z,0,d.x).multiplyScalar(width);v.push(p.x+n.x,y,p.z+n.z,p.x-n.x,y,p.z-n.z);if(i<70){const k=i*2;ix.push(k,k+2,k+1,k+1,k+2,k+3)}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(v,3));geo.setIndex(ix);geo.computeVertexNormals();const material=new THREE.MeshStandardMaterial({color,roughness:1,side:THREE.DoubleSide}),m=new THREE.Mesh(geo,material);m.renderOrder=width>1?-20:-19;m.receiveShadow=true;scene.add(m);return path;}
const river=road([[0,-6],[.4,-4],[0,-2],[-.5,0],[.2,2],[.8,5.8]],1.7,0xb54f64);road([[-3.7,-3.4],[0,-3.1],[3.4,-1.1]],.55,0xf1e0bd);road([[-3.5,3],[.1,2.5],[3.4,-1.1]],.6,0xf1e0bd);
const decorations=[];for(let i=0;i<15;i++){const b=cyl(.2,.09,0xd67d87,scene,0,.12,0);b.scale.z=.7;b.renderOrder=-15;decorations.push({mesh:b,phase:i/15})}
const stationGroups={},rings={};
function station(name,color){const pos=STATIONS[name],g=new THREE.Group();g.position.set(pos.x,0,pos.z);scene.add(g);stationGroups[name]=g;cyl(1.36,.18,0xf7e5bb,g,0,.06,0);const ring=new THREE.Mesh(new THREE.RingGeometry(1.42,1.5,48),new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,transparent:true,opacity:.7}));ring.rotation.x=-Math.PI/2;ring.position.y=.17;ring.renderOrder=-10;g.add(ring);rings[name]=ring;
 if(name==='muscle'){box(1.5,1.1,1.3,color,g,0,.67,-.18);const roof=mesh(new THREE.CylinderGeometry(1.1,1.1,.25,4),0x0f5d60,g,0,1.37,-.18);roof.rotation.y=Math.PI/4;box(.75,.85,.12,0x152f3a,g,0,.53,.5);for(let i=-1;i<=1;i+=2){cyl(.15,1.55,0xf7cb69,g,i*.62,.9,-.7);sphere(.17,0xffe8a9,g,i*.62,1.68,-.7)}for(let i=0;i<3;i++){sphere(.26,0x92d4c7,g,(i-1)*.42,1.66,-.15)}}
 else if(name==='fat'){cyl(1,1.15,color,g,0,.72,-.1);cyl(1.05,.16,0xc48b35,g,0,1.28,-.1);box(.62,.7,.1,0x8c5832,g,0,.58,.91);for(let x of [-.55,0,.55])sphere(.28,0xffdf80,g,x,1.47,-.1)}
 else{box(1.6,1.1,1.15,color,g,0,.65,-.1);const dome=sphere(.78,0xa5a1cd,g,0,1.22,-.1);dome.scale.y=.55;box(.7,.8,.1,0x4e466b,g,0,.48,.48);cyl(.16,1.8,0xe4c1ad,g,-.7,.98,-.6)}
 return g;}
station('muscle',0x379a87);station('fat',0xe7b459);station('liver',0x8e85b5);
function worker(color,scale=1){const g=new THREE.Group(),body=new THREE.Group();g.add(body);cyl(.29,.55,color,body,0,.57,0);sphere(.27,0xffe4bc,body,0,1.05,0);const cap=sphere(.3,color,body,0,1.19,0);cap.scale.y=.55;box(.46,.07,.3,color,body,0,1.16,.19);for(let x of [-.105,.105])sphere(.036,0x343331,body,x,1.07,.237);const nose=sphere(.05,0xf2ba95,body,0,1,.26);const legs=[],arms=[];for(let side of [-1,1]){const leg=box(.16,.31,.19,0x305155,body,side*.14,.2,0);legs.push(leg);sphere(.12,0xffe4bc,body,side*.37,.61,.1);const arm=box(.14,.33,.14,color,body,side*.34,.68,0);arms.push(arm)}g.scale.setScalar(scale);g.userData={body,legs,arms};scene.add(g);return g}
const player=worker(0x167b74,1.4);const teammate=worker(0xe0884e,.85);teammate.visible=false;const npcs=[worker(0xc86b62,.7),worker(0x638aa9,.7)];npcs[0].position.set(4.1,0,2.2);npcs[1].position.set(-4.1,0,.2);
const shadow=new THREE.Mesh(new THREE.CircleGeometry(.52,24),new THREE.MeshBasicMaterial({color:0x543b42,transparent:true,opacity:.2}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.08;shadow.renderOrder=-9;scene.add(shadow);
const cargoGroup=new THREE.Group();player.add(cargoGroup);let cargoSignature='';const itemMeshes=new Map(),flights=[],bursts=[];const cubeGeo=new THREE.BoxGeometry(.52,.52,.52),ldlGeo=new THREE.IcosahedronGeometry(.28,1);
function itemMesh(type){const m=new THREE.Mesh(type==='sugar'?cubeGeo:ldlGeo,mat(type==='sugar'?0xffd259:0xa69ae6));m.castShadow=true;return m}
function reconcileItems(now){const current=new Set(sim.items.map(t=>t.id));for(const [id,m]of itemMeshes)if(!current.has(id)){scene.remove(m);itemMeshes.delete(id)}for(const t of sim.items){let m=itemMeshes.get(t.id);if(!m){m=itemMesh(t.type);scene.add(m);itemMeshes.set(t.id,m)}m.position.set(t.x,.4+Math.sin(now*3+t.seed)*.06,t.z);m.rotation.y=now*.7+t.seed;}const sig=sim.cargo.map(x=>x.id).join(',');if(sig!==cargoSignature){cargoSignature=sig;cargoGroup.clear();sim.cargo.forEach((t,i)=>{const m=itemMesh(t.type);m.position.set((i%2-.5)*.4,.75+Math.floor(i/2)*.35,-.35);cargoGroup.add(m)})}cargoGroup.rotation.z=Math.sin(now*8)*speed*.045;}
function flight(item,from,to){const m=itemMesh(item.type);m.position.copy(from);scene.add(m);flights.push({m,from:from.clone(),to:to.clone(),t:0})}
function particles(pos,color){for(let i=0;i<8;i++){const m=mesh(new THREE.IcosahedronGeometry(.07,0),color,scene,pos.x,pos.y,pos.z);bursts.push({m,t:0,v:new THREE.Vector3((Math.random()-.5)*3,2+Math.random()*2,(Math.random()-.5)*3)})}}
let sound=false,audio;function beep(freq=600){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.14)}catch{}}
const discoveries={storage:{title:'余ったエネルギーは、貯蔵庫へ。',copy:'使いきれないエネルギーは脂肪として蓄えられます。次は、蓄積が進んだ街を見てみよう。',label:'発見 01｜余りが、蓄積につながる'},insulin:{title:'工場の入口が、ゆっくりに。',copy:'脂肪の増えすぎで糖を取り込みにくくなる状態を、入口で表現しています。',label:'発見 02｜糖を取り込みにくくなる'},lipids:{title:'糖だけでなく、脂質のバランスにも。',copy:'脂肪の蓄積やインスリンの効きにくさは、LDLなどの脂質の変化にも関わります。紫の荷物は肝臓へ届けよう。',label:'発見 03｜３つは、別々の話じゃない'}};
let loaded=true,clock=0,last=performance.now(),speed=0,stick=null,destination=null,visible=true,messageUntil=0,paused=false,discoveryUntil=0;const keys=new Set();const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0);let dragDistance=0;
function resize(){const r=$('playfield').getBoundingClientRect();renderer.setSize(r.width,r.height,false);const aspect=r.width/r.height;const halfW=Math.max(6.25,5.7*aspect),halfH=halfW/aspect;camera.left=-halfW;camera.right=halfW;camera.top=halfH;camera.bottom=-halfH;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('playfield'));resize();
function start(){sim.reset();sim.start();$('intro').hidden=true;$('result').hidden=true;$('discovery').hidden=true;paused=false;destination=null;$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','一時停止');messageUntil=0;discoveryUntil=0;stick=null;keys.clear();$('magnet').disabled=false;$('helper').disabled=false;teammate.visible=false;track('game_start');}
const canvas=$('world-canvas');canvas.addEventListener('pointerdown',e=>{if(sim.phase!=='play'||sim.paused)return;e.preventDefault();canvas.focus();canvas.setPointerCapture(e.pointerId);stick={x:e.clientX,y:e.clientY,dx:0,dy:0};dragDistance=0;destination=null;const b=$('playfield').getBoundingClientRect();$('joystick').hidden=false;$('joystick').style.left=e.clientX-b.left+'px';$('joystick').style.top=e.clientY-b.top+'px';});canvas.addEventListener('pointermove',e=>{if(!stick)return;const dx=e.clientX-stick.x,dy=e.clientY-stick.y;dragDistance=Math.max(dragDistance,Math.hypot(dx,dy));const n=Math.max(1,Math.hypot(dx,dy)/43);stick.dx=dx/n/43;stick.dy=dy/n/43;$('joystick').firstElementChild.style.transform=`translate(${stick.dx*28}px,${stick.dy*28}px)`;});
function release(e){if(!stick)return;if(dragDistance<8){const b=canvas.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);raycaster.setFromCamera(pointer,camera);const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(ground,p))destination={x:clamp(p.x,-4.7,4.7),z:clamp(p.z,-5,4.9)}}stick=null;$('joystick').hidden=true;}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',()=>{stick=null;destination=null;$('joystick').hidden=true});canvas.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);destination=null}});canvas.addEventListener('keyup',e=>keys.delete(e.key));canvas.addEventListener('blur',()=>keys.clear());
function message(s,seconds=3){$('world-message').textContent=s;messageUntil=clock+seconds;}
function projected(pos){const p=pos.clone().project(camera),b=$('playfield').getBoundingClientRect();return{x:(p.x+1)/2*b.width,y:(1-p.y)/2*b.height}}
function labels(){for(const name of ['muscle','fat','liver']){const s=STATIONS[name],p=projected(new THREE.Vector3(s.x,1.9,s.z));const el=$('label-'+name);el.hidden=name==='fat'?!sim.rush:name==='liver'?!sim.seen.has('lipids'):false;stationGroups[name].visible=!el.hidden;el.style.left=p.x+'px';el.style.top=p.y+'px';}const hasSugar=sim.cargo.some(x=>x.type==='sugar'),hasLdl=sim.cargo.some(x=>x.type==='ldl');const target=hasSugar?STATIONS.muscle:hasLdl?STATIONS.liver:sim.items[0]||null;const pp=projected(player.position.clone().add(new THREE.Vector3(0,-.7,0)));$('player-label').style.left=pp.x+'px';$('player-label').style.top=pp.y+'px';$('player-label').hidden=sim.score>0;for(const n of ['muscle','liver']){rings[n].material.opacity=(n==='muscle'&&hasSugar||n==='liver'&&hasLdl)? .7+Math.sin(clock*6)*.3:.22;}$('target-mark').hidden=!target||sim.phase!=='play';if(target){const p=projected(new THREE.Vector3(target.x,target===STATIONS.muscle||target===STATIONS.liver?2.8:1.2,target.z));$('target-mark').style.left=p.x+'px';$('target-mark').style.top=p.y+'px';}}
function updateUI(){const s=sim.snapshot();$('score').textContent=s.deliveries;$('timer').textContent=Math.max(0,Math.ceil(60-sim.time))+'秒';$('carry').textContent='荷物 '+s.cargo+' / '+s.capacity;$('carry').classList.toggle('full',s.cargo>=s.capacity);$('sugar-meter').style.width=Math.min(100,s.sugar*4)+'%';$('fat-meter').style.width=Math.min(100,s.fat*5)+'%';$('chol-meter').style.width=Math.min(100,s.ldl*8)+'%';$('storage-count').textContent='蓄積 '+s.fat;$('magnet-note').textContent=sim.magnetCooldown>0?'あと '+Math.ceil(sim.magnetCooldown)+' 秒':'近くの荷物を一気に！';$('magnet').disabled=sim.magnetCooldown>0||sim.phase!=='play'||sim.paused;$('helper').disabled=sim.score<5||sim.helper||sim.phase!=='play'||sim.paused;$('helper-note').textContent=sim.helper?'応援中！ 荷物上限12個':sim.score>=5?'解放！タップでチーム増員':'お届け '+sim.score+' / 5個で解放';
 if(clock>messageUntil&&sim.phase==='play'){$('world-message').textContent=sim.cargo.length>=sim.capacity?'荷物いっぱい！ 工場か肝臓へ届けよう':sim.cargo.some(x=>x.type==='sugar')?'黄色い荷物を、右の筋肉工場へ！':sim.cargo.some(x=>x.type==='ldl')?'紫のLDLを、左上の肝臓へ！':'道の荷物に近づくと、自動で回収！'}
 $('wave-label').textContent=sim.seen.has('lipids')?'03 / ２色を仕分けよう':sim.rush?'02 / 食後のラッシュ':'01 / はじめてのお届け';
 $('mission-title').textContent=sim.cargo.some(x=>x.type==='sugar')?'黄色を工場へ！':sim.cargo.some(x=>x.type==='ldl')?'紫を肝臓へ！':sim.score===0?'黄色い糖を拾おう！':'荷物を集めよう！';
 $('magnet').hidden=sim.score<3;$('helper').hidden=sim.score<5;
 $('fat-meter').parentElement.parentElement.hidden=!sim.rush;$('chol-meter').parentElement.parentElement.hidden=!sim.seen.has('lipids');
 $('storage-count').textContent=sim.insulin>0?'ふくらんでいる':sim.fat>2?'余りを貯蔵':'余りを貯蔵';
 if(clock>discoveryUntil)$('discovery').hidden=true;

}
function processEvents(){for(const e of sim.events.splice(0)){if(e.type==='rush'){message('食後のラッシュ！ 荷物が増えるよ',4)}if(e.type==='collect'){beep(600+sim.cargo.length*45)}if(e.type==='store'){flight(e.item,new THREE.Vector3(e.item.x,.4,e.item.z),new THREE.Vector3(STATIONS.fat.x,1.5,STATIONS.fat.z));}if(e.type==='deliver'){const p=STATIONS[e.station];flight(e.item,e.helper?new THREE.Vector3(e.item.x,.5,e.item.z):player.position.clone().add(new THREE.Vector3(0,1,0)),new THREE.Vector3(p.x,.7,p.z));particles(new THREE.Vector3(p.x,1.5,p.z),0xffe58e);beep(850+Math.min(e.combo,8)*50);if(e.combo>=3){$('combo').hidden=false;$('combo').textContent=e.combo+' COMBO!';$('combo').classList.remove('show');void $('combo').offsetWidth;$('combo').classList.add('show');setTimeout(()=>$('combo').hidden=true,1100)}message(e.combo>=3?'まとめてお届け！ '+e.combo+'連続！':'お届け完了！ +1',1.5)}if(e.type==='magnet'){particles(player.position.clone().add(new THREE.Vector3(0,.7,0)),0x9bede1);message('まとめて回収！ お届け先へGO！');beep(1100)}if(e.type==='helper'){teammate.visible=true;message('応援スタッフ到着！ 荷物も12個に拡張！',4)}if(e.type==='discovery'){const d=e.key==='lipids'&&!sim.seen.has('insulin')?{title:'紫はLDL。肝臓へ運ぼう。',copy:'LDLはコレステロールを運び、肝臓が回収に関わります。',label:'新しいおしごと'}:discoveries[e.key];$('discovery-kicker').textContent=d.label;$('discovery-title').textContent=d.title;$('discovery-copy').textContent=d.copy;$('discovery').hidden=false;discoveryUntil=clock+6;track('relationship_discovery',{topic:e.key});}if(e.type==='end'){end()}}}
function end(){$('result').hidden=false;$('discovery').hidden=true;$('result-summary').innerHTML='<b>体内の働きを、毎日の一杯へ。</b><span>糖の利用・脂肪の蓄積・脂質の調整。<br>３つが気になる方のためのコーヒーをご紹介。</span>';$('result-count').textContent=sim.score;$('result-combo').textContent='最高 '+sim.bestCombo+' 連続';$('result-stars').textContent=sim.score>=25?'★★★':sim.score>=12?'★★☆':'★☆☆';$('magnet').disabled=true;$('helper').disabled=true;track('game_complete',{deliveries:sim.score,combo:sim.bestCombo});}
function track(event,data={}){window.dataLayer??=[];window.dataLayer.push({event,...data})}
function showProduct(){sim.paused=true;stick=null;keys.clear();$('joystick').hidden=true;document.dispatchEvent(new Event('open-product'));track('product_view')}
$('start').onclick=start;$('discovery-next').onclick=()=>{$('discovery').hidden=true;sim.resumeDiscovery();};$('magnet').onclick=()=>sim.magnet();$('helper').onclick=()=>sim.callHelper();$('pause').onclick=()=>{if(sim.phase!=='play')return;sim.paused=!sim.paused;$('pause').textContent=sim.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',sim.paused?'再開':'一時停止');stick=null;keys.clear();$('joystick').hidden=true;if(sim.paused)message('ひと休み中。右上の ▶ で再開。',999);else messageUntil=0;};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'音 ON':'音 OFF';$('sound').setAttribute('aria-pressed',sound);beep()};$('skip').onclick=showProduct;$('to-product').onclick=showProduct;$('home').onclick=e=>{e.preventDefault();start()};$('play-again').onclick=start;$('reload-game').onclick=()=>location.reload();$('fallback-product').onclick=showProduct;document.addEventListener('replay-game',()=>{start();$('game').scrollIntoView({behavior:'smooth'})});
new IntersectionObserver(e=>{visible=e[0].isIntersecting;},{threshold:.15}).observe($('game'));document.addEventListener('visibilitychange',()=>{last=performance.now();stick=null;keys.clear();$('joystick').hidden=true});
// Visible relation links: storage -> glucose handling and storage -> lipid processing.
const linkCurves=[];for(const name of ['muscle','liver']){const a=STATIONS.fat,b=STATIONS[name];const curve=new THREE.QuadraticBezierCurve3(new THREE.Vector3(a.x,1.7,a.z),new THREE.Vector3(0,3,0),new THREE.Vector3(b.x,1.9,b.z));const geom=new THREE.BufferGeometry().setFromPoints(curve.getPoints(40));const m=new THREE.LineDashedMaterial({color:name==='muscle'?0x087c6c:0x7761b8,dashSize:.2,gapSize:.13,transparent:true,opacity:.7});const line=new THREE.Line(geom,m);line.computeLineDistances();line.visible=false;scene.add(line);const dot=sphere(.13,name==='muscle'?0x57bea3:0xa68ddd,scene,0,0,0);dot.visible=false;linkCurves.push({name,curve,line,dot});}
const gate=box(.6,.6,.15,0xdf774d,stationGroups.muscle,0,.55,.7);gate.visible=false;
function frame(now){const elapsed=Math.max(0,(now-last)/1000),dt=Math.min(.05,elapsed);last=now;clock+=elapsed;if(!document.hidden&&visible){if(sim.phase==='intro'){sim.intro+=elapsed;$('auto-label').textContent='あと'+Math.max(1,Math.ceil(5-sim.intro))+'秒で自動スタート';if(sim.intro>=5)start()}let dx=stick?.dx||0,dz=stick?.dy||0;if(keys.has('ArrowLeft')||keys.has('a'))dx=-1;if(keys.has('ArrowRight')||keys.has('d'))dx=1;if(keys.has('ArrowUp')||keys.has('w'))dz=-1;if(keys.has('ArrowDown')||keys.has('s'))dz=1;if(destination){dx=destination.x-sim.player.x;dz=destination.z-sim.player.z;const length=Math.hypot(dx,dz);if(length<.12){destination=null;dx=0;dz=0}else{dx/=length;dz/=length}}sim.move(dx,dz,dt);speed=sim.phase==='play'&&!sim.paused?Math.min(1,Math.hypot(dx,dz)):0;sim.tick(elapsed);processEvents();player.position.set(sim.player.x,0,sim.player.z);shadow.position.set(sim.player.x,.07,sim.player.z);if(speed>.05){const angle=Math.atan2(dx,dz);let diff=Math.atan2(Math.sin(angle-player.rotation.y),Math.cos(angle-player.rotation.y));player.rotation.y+=diff*Math.min(1,dt*13)}player.userData.body.position.y=Math.abs(Math.sin(clock*12))*.07*speed;player.userData.legs.forEach((l,i)=>l.rotation.x=Math.sin(clock*12+i*Math.PI)*speed*.6);player.userData.arms.forEach((l,i)=>l.rotation.x=Math.sin(clock*12+i*Math.PI+Math.PI)*speed*.4);
 teammate.position.set(2.4+Math.sin(clock)*.5,0,-2.5+Math.cos(clock)*.6);teammate.rotation.y=clock;for(const [i,n]of npcs.entries()){n.userData.body.position.y=Math.sin(clock*2+i)*.035;n.rotation.y=Math.sin(clock*.5+i)*.5}
 reconcileItems(clock);for(const r of decorations){const p=river.getPoint((r.phase+clock*.022)%1);r.mesh.position.set(p.x+Math.sin(r.phase*99)*.9,.13,p.z)}for(let i=flights.length-1;i>=0;i--){const f=flights[i];f.t+=dt*2.7;f.m.position.lerpVectors(f.from,f.to,Math.min(1,f.t));f.m.position.y+=Math.sin(f.t*Math.PI)*1.1;f.m.rotation.y+=dt*7;if(f.t>=1){scene.remove(f.m);flights.splice(i,1)}}for(let i=bursts.length-1;i>=0;i--){const b=bursts[i];b.t+=dt;b.v.y-=dt*6;b.m.position.addScaledVector(b.v,dt);b.m.scale.setScalar(Math.max(.01,1-b.t));if(b.t>1){scene.remove(b.m);b.m.geometry.dispose();bursts.splice(i,1)}}stationGroups.fat.scale.y=1+Math.min(.45,sim.fat*.02);gate.visible=sim.insulin>.12;gate.scale.x=1+sim.insulin;gate.position.y=.55+Math.sin(clock*2)*.07;for(const l of linkCurves){const on=sim.seen.has(l.name==='muscle'?'insulin':'lipids');l.line.visible=l.dot.visible=on;if(on)l.dot.position.copy(l.curve.getPoint((clock*.2)%1));}labels();updateUI();renderer.render(scene,camera);}requestAnimationFrame(frame)}requestAnimationFrame(frame);
if(document.modelContext?.registerTool){const life=new AbortController();const definitions=[{name:'read_body_city_game',description:'Read current game state and delivery score.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(Object.keys(input).length)throw Error('No arguments expected');return sim.snapshot()}},{name:'navigate_body_city',description:'Move the delivery worker to a named visible station, collecting along the way.',inputSchema:{type:'object',properties:{station:{type:'string',enum:['muscle','liver','fat','center']}},required:['station'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!['muscle','liver','fat','center'].includes(input.station)||Object.keys(input).length!==1)throw Error('Invalid station');if(sim.phase!=='play'||sim.paused)throw Error('Game is not active');destination=input.station==='center'?{x:0,z:0}:{...STATIONS[input.station]};return {movingTo:input.station}}}];for(const t of definitions)try{Promise.resolve(document.modelContext.registerTool(t,{signal:life.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
